//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refractor.UnitTestGenerator.Properties {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class PropertyTestGenerator : PropertyTestGeneratorBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 ""
            this.Write("namespace ");
            
            #line default
            #line hidden
            
            #line 6 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(TestNamespace));
            
            #line default
            #line hidden
            
            #line 6 ""
            this.Write(" {\n\n    using System;\n    using Microsoft.VisualStudio.TestTools.UnitTesting;\n\n  " +
                    "  [TestClass]\n    public partial class ");
            
            #line default
            #line hidden
            
            #line 12 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 12 ""
            this.Write(" {\n    \n    private ");
            
            #line default
            #line hidden
            
            #line 14 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassNameUnderTest));
            
            #line default
            #line hidden
            
            #line 14 ""
            this.Write(" classUnderTest;\n\n    [TestInitialize]\n    public void TestInitialize() {\n    \n  " +
                    "      // Arrannge\n        classUnderTest = new ");
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassNameUnderTest));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("();\n    \n    }\n    \n    [TestCleanup]\n    public void TestCleanup() {\n    \n      " +
                    "  // Clear up after tests\n        classUnderTest = default;\n    \n    }\n    \n    " +
                    "");
            
            #line default
            #line hidden
            
            #line 32 ""
 foreach(var propertyTestData in PropertyTestData) { 
    var propertyValues = GetTestValuesForType(propertyTestData.PropertyType);  
    foreach(var propertyValue in propertyValues) { 
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write("[DataRow(");
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyValue));
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyValue));
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(")]\n    ");
            
            #line default
            #line hidden
            
            #line 36 ""
 } 
            
            #line default
            #line hidden
            
            #line 37 ""
            this.Write("[DataTestMethod]\n    public void ");
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyTestData.PropertyName));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write("_GetAndSet(");
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyTestData.PropertyTypeName));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(" input, ");
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyTestData.PropertyTypeName));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(" expected) {\n        \n        // Act\n        classUnderTest.");
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyTestData.PropertyName));
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write(" = input;\n        \n        // Assert\n        Assert.AreEqual(expected, classUnder" +
                    "Test.");
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyTestData.PropertyName));
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write(");\n    }\n    \n    ");
            
            #line default
            #line hidden
            
            #line 47 ""
 
    } // End of PropertyTestData foreach loop 
    
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write("    \n    } // End of class ");
            
            #line default
            #line hidden
            
            #line 51 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 51 ""
            this.Write("\n\n} // End of namespace ");
            
            #line default
            #line hidden
            
            #line 53 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(TestNamespace));
            
            #line default
            #line hidden
            
            #line 53 ""
            this.Write("\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class PropertyTestGeneratorBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
